### ISSUE TITLE
SQL logic error: view logbook_view already exists (1)

### ISSUE THREAD

**Issue by arthur-ver** [vsimakhin/web-logbook#269]
Hi!

First of all, thanks for your amazing work! :)

I've updated to v2.44.0 and after running `docker run --rm -it -p 4000:4000 -v /root/data:/data vsimakhin/web-logbook:v2.44.0` I get this error:

```
SQL logic error: no such table: metadata (1)
ERROR	2024/12/13 17:47:27 main.go:162: SQL logic error: view logbook_view already exists (1)
```

**Comment by vsimakhin** [comment]
Hey!

Wow, that looks like a nice glitch because in theory there cannot (or shouldn't) be these two errors in a row :)

Does the error still appear if you restart the app? And what version did you use before?

**Comment by arthur-ver** [comment]
It's a clean install on Debian 12 using Docker. I actually wanted to start with v2.44.0, and was getting another error `Error: Unable to open database file: out of memory (14)`. Then I tried v2.43.3 with no errors and after that I tried running v2.44.0 again and got `ERROR	2024/12/13 17:47:27 main.go:162: SQL logic error: view logbook_view already exists (1)`

**Comment by vsimakhin** [comment]
Ok, I tried to reproduce it...

So the error `Error: Unable to open database file: out of memory (14)` usually occurs when you set the data path to the directory where you have no write rights, for example in your case `/root/data`

```bash
$ mkdir -p /tmp/logbook/data
$ cdmod 0400 /tmp/logbook/data
$ docker run --rm -it -p 4000:4000 -v /tmp/logbook/data:/data vsimakhin/web-logbook:v2.44.0
ERROR	2024/12/14 20:19:38 main.go:162: unable to open database file: out of memory (14)
```

the `/tmp/logbook/data` directory was empty.

Then I tried to run 2.43.3 version
```bash
$ docker run --rm -it -p 4000:4000 -v /tmp/logbook/data:/data vsimakhin/web-logbook:v2.43.3
INFO	2024/12/14 20:21:26 Web Logbook v2.43.3 is ready on http://localhost:4000
```
after that run the `/tmp/logbook/data` contains the web-logbook.sql, but without proper permissions. It happens because previous versions of the docker image didn't change the user and everything was running under root. I updated the Dockerfile recently to use a new approach (more "cloud native" style) and also to build for multiarch - https://github.com/vsimakhin/web-logbook/blob/main/docker/build.Dockerfile#L23

So if I'm right the owner of your `/root/data/web-logbook.sql` is root now. And to fix it you just need to run `sudo chown $(whoami):$(whoami) /root/data/web-logbook.sql ` (basically change the owner to current user)

**Comment by vsimakhin** [comment]
I've updated readme and changelog with **BREAKING** statement based on your findings. Thanks!

**Comment by arthur-ver** [comment]
Thanks for the reply! I only have one user on my cloud VM which is `root`.
```
-rw-r--r-- 1 root root 1650688 Dec 14 22:33 web-logbook.sql
```

Weird that Docker doesn't have write access to the file. What should I change in my case then?

**Comment by vsimakhin** [comment]
Hm, that's weird. Can you try to run `chmod 0666 ./web-logbook.sql`. It will add read/write access for all users and groups

**Comment by arthur-ver** [comment]
I tried setting `chmod 0666 data/web-logbook.sql` and the error remains:

```
web-logbook-1  | SQL logic error: no such table: metadata (1)
web-logbook-1  | ERROR	2024/12/15 20:10:12 main.go:162: SQL logic error: view logbook_view already exists (1)
web-logbook-1 exited with code 1
```

When I also set `chmod 0666 data` as well I get this error:
```
web-logbook-1  | ERROR	2024/12/15 20:11:30 main.go:162: unable to open database file: out of memory (14)
```

**Comment by arthur-ver** [comment]
It seems to be working now after running `chmod -R a+rwx ./data`. Thanks for your help! :)

**Comment by vsimakhin** [comment]
Ah, my bad, forgot about the rights for the directory. Glad it's working now!
